development:
  adapter: mysql2
  host: localhost
  database: blog
  username: root
  password: zy
  pool: 5
  timeout: 5000
test:
  adapter: mysql2
  host: localhost
  database: blog_test
  username: root
  password: zy
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  host: localhost
  username: root
  password: zy
  database: blog
  pool: 5
  timeout: 5000
